# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: hcadminservice
services:
  mongodb:
    image: mongo:8
    env_file: mongo.env
    ports:
      - 127.0.0.1:27017:27017
    # volumes:
    #   - ~/volumes/jhipster/hcadminservice/mongodb/:/data/db/
    healthcheck:
      test: ['CMD', 'echo', '''db.runCommand("ping").ok''', '|', 'mongo', 'localhost:27017/test', '--quiet']
      interval: 5s
      timeout: 5s
      retries: 10
