package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AngelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAngelAllPropertiesEquals(Angel expected, Angel actual) {
        assertAngelAutoGeneratedPropertiesEquals(expected, actual);
        assertAngelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAngelAllUpdatablePropertiesEquals(Angel expected, Angel actual) {
        assertAngelUpdatableFieldsEquals(expected, actual);
        assertAngelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAngelAutoGeneratedPropertiesEquals(Angel expected, Angel actual) {
        assertThat(actual)
            .as("Verify Angel auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAngelUpdatableFieldsEquals(Angel expected, Angel actual) {
        assertThat(actual)
            .as("Verify Angel relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getRelationship()).as("check relationship").isEqualTo(expected.getRelationship()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAngelUpdatableRelationshipsEquals(Angel expected, Angel actual) {
        // empty method
    }
}
