package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AuditEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditEntryAllPropertiesEquals(AuditEntry expected, AuditEntry actual) {
        assertAuditEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertAuditEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditEntryAllUpdatablePropertiesEquals(AuditEntry expected, AuditEntry actual) {
        assertAuditEntryUpdatableFieldsEquals(expected, actual);
        assertAuditEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditEntryAutoGeneratedPropertiesEquals(AuditEntry expected, AuditEntry actual) {
        assertThat(actual)
            .as("Verify AuditEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditEntryUpdatableFieldsEquals(AuditEntry expected, AuditEntry actual) {
        assertThat(actual)
            .as("Verify AuditEntry relevant properties")
            .satisfies(a -> assertThat(a.getOccurredAt()).as("check occurredAt").isEqualTo(expected.getOccurredAt()))
            .satisfies(a -> assertThat(a.getActor()).as("check actor").isEqualTo(expected.getActor()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getTarget()).as("check target").isEqualTo(expected.getTarget()))
            .satisfies(a -> assertThat(a.getLevel()).as("check level").isEqualTo(expected.getLevel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditEntryUpdatableRelationshipsEquals(AuditEntry expected, AuditEntry actual) {
        // empty method
    }
}
