package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CareActivityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareActivityAllPropertiesEquals(CareActivity expected, CareActivity actual) {
        assertCareActivityAutoGeneratedPropertiesEquals(expected, actual);
        assertCareActivityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareActivityAllUpdatablePropertiesEquals(CareActivity expected, CareActivity actual) {
        assertCareActivityUpdatableFieldsEquals(expected, actual);
        assertCareActivityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareActivityAutoGeneratedPropertiesEquals(CareActivity expected, CareActivity actual) {
        assertThat(actual)
            .as("Verify CareActivity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareActivityUpdatableFieldsEquals(CareActivity expected, CareActivity actual) {
        assertThat(actual)
            .as("Verify CareActivity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getOccurredOn()).as("check occurredOn").isEqualTo(expected.getOccurredOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCareActivityUpdatableRelationshipsEquals(CareActivity expected, CareActivity actual) {
        assertThat(actual)
            .as("Verify CareActivity relationships")
            .satisfies(a -> assertThat(a.getPatient()).as("check patient").isEqualTo(expected.getPatient()));
    }
}
