package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */

    /*
     * createdBy / createdDate / modifiedBy / modifiedDate are deliberately NOT compared here.
     *
     * They are stamped server-side by AuditingEntityCallback and are no longer part of the contract
     * a client controls, so asserting that a value sent in a request comes back unchanged would be
     * asserting the vulnerability this replaced — any caller could PUT "modifiedBy":"somebody-else"
     * and have it stored as authoritative. The stamping behaviour itself is covered by AuditingIT.
     */
    public static void assertDocumentItemAllPropertiesEquals(DocumentItem expected, DocumentItem actual) {
        assertDocumentItemAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentItemAllUpdatablePropertiesEquals(DocumentItem expected, DocumentItem actual) {
        assertDocumentItemUpdatableFieldsEquals(expected, actual);
        assertDocumentItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentItemAutoGeneratedPropertiesEquals(DocumentItem expected, DocumentItem actual) {
        assertThat(actual)
            .as("Verify DocumentItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentItemUpdatableFieldsEquals(DocumentItem expected, DocumentItem actual) {
        assertThat(actual)
            .as("Verify DocumentItem relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDocumentType()).as("check documentType").isEqualTo(expected.getDocumentType()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentItemUpdatableRelationshipsEquals(DocumentItem expected, DocumentItem actual) {
        // empty method
    }
}
