package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FacilityCatalogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityCatalogAllPropertiesEquals(FacilityCatalog expected, FacilityCatalog actual) {
        assertFacilityCatalogAutoGeneratedPropertiesEquals(expected, actual);
        assertFacilityCatalogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityCatalogAllUpdatablePropertiesEquals(FacilityCatalog expected, FacilityCatalog actual) {
        assertFacilityCatalogUpdatableFieldsEquals(expected, actual);
        assertFacilityCatalogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityCatalogAutoGeneratedPropertiesEquals(FacilityCatalog expected, FacilityCatalog actual) {
        assertThat(actual)
            .as("Verify FacilityCatalog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityCatalogUpdatableFieldsEquals(FacilityCatalog expected, FacilityCatalog actual) {
        assertThat(actual)
            .as("Verify FacilityCatalog relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getFacilities()).as("check facilities").isEqualTo(expected.getFacilities()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityCatalogUpdatableRelationshipsEquals(FacilityCatalog expected, FacilityCatalog actual) {
        // empty method
    }
}
