package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FacilityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */

    /*
     * createdBy / createdDate / modifiedBy / modifiedDate are deliberately NOT compared here.
     *
     * They are stamped server-side by AuditingEntityCallback and are no longer part of the contract
     * a client controls, so asserting that a value sent in a request comes back unchanged would be
     * asserting the vulnerability this replaced — any caller could PUT "modifiedBy":"somebody-else"
     * and have it stored as authoritative. The stamping behaviour itself is covered by AuditingIT.
     */
    public static void assertFacilityAllPropertiesEquals(Facility expected, Facility actual) {
        assertFacilityAutoGeneratedPropertiesEquals(expected, actual);
        assertFacilityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityAllUpdatablePropertiesEquals(Facility expected, Facility actual) {
        assertFacilityUpdatableFieldsEquals(expected, actual);
        assertFacilityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityAutoGeneratedPropertiesEquals(Facility expected, Facility actual) {
        assertThat(actual)
            .as("Verify Facility auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityUpdatableFieldsEquals(Facility expected, Facility actual) {
        assertThat(actual)
            .as("Verify Facility relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getAddressId()).as("check addressId").isEqualTo(expected.getAddressId()))
            .satisfies(a -> assertThat(a.getContactId()).as("check contactId").isEqualTo(expected.getContactId()))
            .satisfies(a -> assertThat(a.getPhotos()).as("check photos").isEqualTo(expected.getPhotos()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacilityUpdatableRelationshipsEquals(Facility expected, Facility actual) {
        // empty method
    }
}
