package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HCProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */

    /*
     * createdBy / createdDate / modifiedBy / modifiedDate are deliberately NOT compared here.
     *
     * They are stamped server-side by AuditingEntityCallback and are no longer part of the contract
     * a client controls, so asserting that a value sent in a request comes back unchanged would be
     * asserting the vulnerability this replaced — any caller could PUT "modifiedBy":"somebody-else"
     * and have it stored as authoritative. The stamping behaviour itself is covered by AuditingIT.
     */
    public static void assertProfileAllPropertiesEquals(HCProfile expected, HCProfile actual) {
        assertProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileAllUpdatablePropertiesEquals(HCProfile expected, HCProfile actual) {
        assertProfileUpdatableFieldsEquals(expected, actual);
        assertProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileAutoGeneratedPropertiesEquals(HCProfile expected, HCProfile actual) {
        assertThat(actual)
            .as("Verify Profile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileUpdatableFieldsEquals(HCProfile expected, HCProfile actual) {
        assertThat(actual)
            .as("Verify Profile relevant properties")
            .satisfies(a -> assertThat(a.getPersonId()).as("check personId").isEqualTo(expected.getPersonId()))
            .satisfies(a -> assertThat(a.getPhotoId()).as("check photoId").isEqualTo(expected.getPhotoId()))
            .satisfies(a -> assertThat(a.getContactId()).as("check contactId").isEqualTo(expected.getContactId()))
            .satisfies(a -> assertThat(a.getAddressList()).as("check addressList").isEqualTo(expected.getAddressList()))
            .satisfies(a -> assertThat(a.getRoles()).as("check roles").isEqualTo(expected.getRoles()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getOrganisationId()).as("check organisationId").isEqualTo(expected.getOrganisationId()))
            .satisfies(a -> assertThat(a.getTeamId()).as("check teamId").isEqualTo(expected.getTeamId()))
            .satisfies(a -> assertThat(a.getDocumentItems()).as("check documentItems").isEqualTo(expected.getDocumentItems()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileUpdatableRelationshipsEquals(HCProfile expected, HCProfile actual) {
        // empty method
    }
}
