package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HCProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileAllPropertiesEquals(HCProfile expected, HCProfile actual) {
        assertProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileAllUpdatablePropertiesEquals(HCProfile expected, HCProfile actual) {
        assertProfileUpdatableFieldsEquals(expected, actual);
        assertProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileAutoGeneratedPropertiesEquals(HCProfile expected, HCProfile actual) {
        assertThat(actual)
            .as("Verify Profile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileUpdatableFieldsEquals(HCProfile expected, HCProfile actual) {
        assertThat(actual)
            .as("Verify Profile relevant properties")
            .satisfies(a -> assertThat(a.getPersonId()).as("check personId").isEqualTo(expected.getPersonId()))
            .satisfies(a -> assertThat(a.getPhotoId()).as("check photoId").isEqualTo(expected.getPhotoId()))
            .satisfies(a -> assertThat(a.getContactId()).as("check contactId").isEqualTo(expected.getContactId()))
            .satisfies(a -> assertThat(a.getAddressList()).as("check addressList").isEqualTo(expected.getAddressList()))
            .satisfies(a -> assertThat(a.getRoles()).as("check roles").isEqualTo(expected.getRoles()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getOrganisationId()).as("check organisationId").isEqualTo(expected.getOrganisationId()))
            .satisfies(a -> assertThat(a.getTeamId()).as("check teamId").isEqualTo(expected.getTeamId()))
            .satisfies(a -> assertThat(a.getDocumentItems()).as("check documentItems").isEqualTo(expected.getDocumentItems()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getModifiedBy()).as("check modifiedBy").isEqualTo(expected.getModifiedBy()))
            .satisfies(a -> assertThat(a.getModifiedDate()).as("check modifiedDate").isEqualTo(expected.getModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileUpdatableRelationshipsEquals(HCProfile expected, HCProfile actual) {
        // empty method
    }
}
