package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HCServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */

    /*
     * createdBy / createdDate / modifiedBy / modifiedDate are deliberately NOT compared here.
     *
     * They are stamped server-side by AuditingEntityCallback and are no longer part of the contract
     * a client controls, so asserting that a value sent in a request comes back unchanged would be
     * asserting the vulnerability this replaced — any caller could PUT "modifiedBy":"somebody-else"
     * and have it stored as authoritative. The stamping behaviour itself is covered by AuditingIT.
     */
    public static void assertHCServiceAllPropertiesEquals(HCService expected, HCService actual) {
        assertHCServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertHCServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCServiceAllUpdatablePropertiesEquals(HCService expected, HCService actual) {
        assertHCServiceUpdatableFieldsEquals(expected, actual);
        assertHCServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCServiceAutoGeneratedPropertiesEquals(HCService expected, HCService actual) {
        assertThat(actual)
            .as("Verify HCService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCServiceUpdatableFieldsEquals(HCService expected, HCService actual) {
        assertThat(actual)
            .as("Verify HCService relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getServiceItems()).as("check serviceItems").isEqualTo(expected.getServiceItems()))
            .satisfies(a -> assertThat(a.getAmount()).as("check amount").isEqualTo(expected.getAmount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCServiceUpdatableRelationshipsEquals(HCService expected, HCService actual) {
        // empty method
    }
}
