package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HCSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCSubscriptionAllPropertiesEquals(HCSubscription expected, HCSubscription actual) {
        assertHCSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertHCSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCSubscriptionAllUpdatablePropertiesEquals(HCSubscription expected, HCSubscription actual) {
        assertHCSubscriptionUpdatableFieldsEquals(expected, actual);
        assertHCSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCSubscriptionAutoGeneratedPropertiesEquals(HCSubscription expected, HCSubscription actual) {
        assertThat(actual)
            .as("Verify HCSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCSubscriptionUpdatableFieldsEquals(HCSubscription expected, HCSubscription actual) {
        assertThat(actual)
            .as("Verify HCSubscription relevant properties")
            .satisfies(a -> assertThat(a.getServiceId()).as("check serviceId").isEqualTo(expected.getServiceId()))
            .satisfies(a -> assertThat(a.getPatientId()).as("check patientId").isEqualTo(expected.getPatientId()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getModifiedDate()).as("check modifiedDate").isEqualTo(expected.getModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getModifiedBy()).as("check modifiedBy").isEqualTo(expected.getModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCSubscriptionUpdatableRelationshipsEquals(HCSubscription expected, HCSubscription actual) {
        // empty method
    }
}
