package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HCSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */

    /*
     * createdBy / createdDate / modifiedBy / modifiedDate are deliberately NOT compared here.
     *
     * They are stamped server-side by AuditingEntityCallback and are no longer part of the contract
     * a client controls, so asserting that a value sent in a request comes back unchanged would be
     * asserting the vulnerability this replaced — any caller could PUT "modifiedBy":"somebody-else"
     * and have it stored as authoritative. The stamping behaviour itself is covered by AuditingIT.
     */
    public static void assertHCSubscriptionAllPropertiesEquals(HCSubscription expected, HCSubscription actual) {
        assertHCSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertHCSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCSubscriptionAllUpdatablePropertiesEquals(HCSubscription expected, HCSubscription actual) {
        assertHCSubscriptionUpdatableFieldsEquals(expected, actual);
        assertHCSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCSubscriptionAutoGeneratedPropertiesEquals(HCSubscription expected, HCSubscription actual) {
        assertThat(actual)
            .as("Verify HCSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCSubscriptionUpdatableFieldsEquals(HCSubscription expected, HCSubscription actual) {
        assertThat(actual)
            .as("Verify HCSubscription relevant properties")
            .satisfies(a -> assertThat(a.getServiceId()).as("check serviceId").isEqualTo(expected.getServiceId()))
            .satisfies(a -> assertThat(a.getPatientId()).as("check patientId").isEqualTo(expected.getPatientId()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHCSubscriptionUpdatableRelationshipsEquals(HCSubscription expected, HCSubscription actual) {
        // empty method
    }
}
