package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HProfessionalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */

    /*
     * createdBy / createdDate / modifiedBy / modifiedDate are deliberately NOT compared here.
     *
     * They are stamped server-side by AuditingEntityCallback and are no longer part of the contract
     * a client controls, so asserting that a value sent in a request comes back unchanged would be
     * asserting the vulnerability this replaced — any caller could PUT "modifiedBy":"somebody-else"
     * and have it stored as authoritative. The stamping behaviour itself is covered by AuditingIT.
     */
    public static void assertHProfessionalAllPropertiesEquals(HProfessional expected, HProfessional actual) {
        assertHProfessionalAutoGeneratedPropertiesEquals(expected, actual);
        assertHProfessionalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHProfessionalAllUpdatablePropertiesEquals(HProfessional expected, HProfessional actual) {
        assertHProfessionalUpdatableFieldsEquals(expected, actual);
        assertHProfessionalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHProfessionalAutoGeneratedPropertiesEquals(HProfessional expected, HProfessional actual) {
        assertThat(actual)
            .as("Verify HProfessional auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHProfessionalUpdatableFieldsEquals(HProfessional expected, HProfessional actual) {
        assertThat(actual)
            .as("Verify HProfessional relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getOrganisation()).as("check organisation").isEqualTo(expected.getOrganisation()))
            .satisfies(a -> assertThat(a.getRoster()).as("check roster").isEqualTo(expected.getRoster()))
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHProfessionalUpdatableRelationshipsEquals(HProfessional expected, HProfessional actual) {
        // empty method
    }
}
