package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HProfessionalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHProfessionalAllPropertiesEquals(HProfessional expected, HProfessional actual) {
        assertHProfessionalAutoGeneratedPropertiesEquals(expected, actual);
        assertHProfessionalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHProfessionalAllUpdatablePropertiesEquals(HProfessional expected, HProfessional actual) {
        assertHProfessionalUpdatableFieldsEquals(expected, actual);
        assertHProfessionalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHProfessionalAutoGeneratedPropertiesEquals(HProfessional expected, HProfessional actual) {
        assertThat(actual)
            .as("Verify HProfessional auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHProfessionalUpdatableFieldsEquals(HProfessional expected, HProfessional actual) {
        assertThat(actual)
            .as("Verify HProfessional relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getOrganisation()).as("check organisation").isEqualTo(expected.getOrganisation()))
            .satisfies(a -> assertThat(a.getRoster()).as("check roster").isEqualTo(expected.getRoster()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getModifiedDate()).as("check modifiedDate").isEqualTo(expected.getModifiedDate()))
            .satisfies(a -> assertThat(a.getModifiedBy()).as("check modifiedBy").isEqualTo(expected.getModifiedBy()))
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHProfessionalUpdatableRelationshipsEquals(HProfessional expected, HProfessional actual) {
        // empty method
    }
}
