package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HubAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHubAllPropertiesEquals(Hub expected, Hub actual) {
        assertHubAutoGeneratedPropertiesEquals(expected, actual);
        assertHubAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHubAllUpdatablePropertiesEquals(Hub expected, Hub actual) {
        assertHubUpdatableFieldsEquals(expected, actual);
        assertHubUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHubAutoGeneratedPropertiesEquals(Hub expected, Hub actual) {
        assertThat(actual)
            .as("Verify Hub auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHubUpdatableFieldsEquals(Hub expected, Hub actual) {
        assertThat(actual)
            .as("Verify Hub relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStaffCount()).as("check staffCount").isEqualTo(expected.getStaffCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHubUpdatableRelationshipsEquals(Hub expected, Hub actual) {
        assertThat(actual)
            .as("Verify Hub relationships")
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()));
    }
}
