package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganisationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationAllPropertiesEquals(Organisation expected, Organisation actual) {
        assertOrganisationAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganisationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationAllUpdatablePropertiesEquals(Organisation expected, Organisation actual) {
        assertOrganisationUpdatableFieldsEquals(expected, actual);
        assertOrganisationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationAutoGeneratedPropertiesEquals(Organisation expected, Organisation actual) {
        assertThat(actual)
            .as("Verify Organisation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationUpdatableFieldsEquals(Organisation expected, Organisation actual) {
        assertThat(actual)
            .as("Verify Organisation relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLegalName()).as("check legalName").isEqualTo(expected.getLegalName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getRegistrationNumber()).as("check registrationNumber").isEqualTo(expected.getRegistrationNumber())
            )
            .satisfies(a -> assertThat(a.getTin()).as("check tin").isEqualTo(expected.getTin()))
            .satisfies(a -> assertThat(a.getFoundedOn()).as("check foundedOn").isEqualTo(expected.getFoundedOn()))
            .satisfies(a -> assertThat(a.getSwitchboard()).as("check switchboard").isEqualTo(expected.getSwitchboard()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getDeskHours()).as("check deskHours").isEqualTo(expected.getDeskHours()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationUpdatableRelationshipsEquals(Organisation expected, Organisation actual) {
        assertThat(actual)
            .as("Verify Organisation relationships")
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()));
    }
}
