package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganisationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */

    /*
     * createdBy / createdDate / modifiedBy / modifiedDate are deliberately NOT compared here.
     *
     * They are stamped server-side by AuditingEntityCallback and are no longer part of the contract
     * a client controls, so asserting that a value sent in a request comes back unchanged would be
     * asserting the vulnerability this replaced — any caller could PUT "modifiedBy":"somebody-else"
     * and have it stored as authoritative. The stamping behaviour itself is covered by AuditingIT.
     */
    public static void assertOrganisationAllPropertiesEquals(Organisation expected, Organisation actual) {
        assertOrganisationAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganisationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationAllUpdatablePropertiesEquals(Organisation expected, Organisation actual) {
        assertOrganisationUpdatableFieldsEquals(expected, actual);
        assertOrganisationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationAutoGeneratedPropertiesEquals(Organisation expected, Organisation actual) {
        assertThat(actual)
            .as("Verify Organisation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationUpdatableFieldsEquals(Organisation expected, Organisation actual) {
        assertThat(actual)
            .as("Verify Organisation relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAddressId()).as("check addressId").isEqualTo(expected.getAddressId()))
            .satisfies(a -> assertThat(a.getContactId()).as("check contactId").isEqualTo(expected.getContactId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganisationUpdatableRelationshipsEquals(Organisation expected, Organisation actual) {
        // empty method
    }
}
