package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PatientPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientPlanAllPropertiesEquals(PatientPlan expected, PatientPlan actual) {
        assertPatientPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertPatientPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientPlanAllUpdatablePropertiesEquals(PatientPlan expected, PatientPlan actual) {
        assertPatientPlanUpdatableFieldsEquals(expected, actual);
        assertPatientPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientPlanAutoGeneratedPropertiesEquals(PatientPlan expected, PatientPlan actual) {
        assertThat(actual)
            .as("Verify PatientPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientPlanUpdatableFieldsEquals(PatientPlan expected, PatientPlan actual) {
        assertThat(actual)
            .as("Verify PatientPlan relevant properties")
            .satisfies(a -> assertThat(a.getPlanId()).as("check planId").isEqualTo(expected.getPlanId()))
            .satisfies(a -> assertThat(a.getPatientId()).as("check patientId").isEqualTo(expected.getPatientId()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPatientPlanUpdatableRelationshipsEquals(PatientPlan expected, PatientPlan actual) {
        // empty method
    }
}
