package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PhotoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */

    /*
     * createdBy / createdDate / modifiedBy / modifiedDate are deliberately NOT compared here.
     *
     * They are stamped server-side by AuditingEntityCallback and are no longer part of the contract
     * a client controls, so asserting that a value sent in a request comes back unchanged would be
     * asserting the vulnerability this replaced — any caller could PUT "modifiedBy":"somebody-else"
     * and have it stored as authoritative. The stamping behaviour itself is covered by AuditingIT.
     */
    public static void assertPhotoAllPropertiesEquals(Photo expected, Photo actual) {
        assertPhotoAutoGeneratedPropertiesEquals(expected, actual);
        assertPhotoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhotoAllUpdatablePropertiesEquals(Photo expected, Photo actual) {
        assertPhotoUpdatableFieldsEquals(expected, actual);
        assertPhotoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhotoAutoGeneratedPropertiesEquals(Photo expected, Photo actual) {
        assertThat(actual)
            .as("Verify Photo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhotoUpdatableFieldsEquals(Photo expected, Photo actual) {
        assertThat(actual)
            .as("Verify Photo relevant properties")
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAltText()).as("check altText").isEqualTo(expected.getAltText()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getProfileId()).as("check profileId").isEqualTo(expected.getProfileId()))
            .satisfies(a -> assertThat(a.getPhotoType()).as("check photoType").isEqualTo(expected.getPhotoType()))
            // isEqualTo on byte[] compares identity, not contents — a passing assertion here would
            // mean the two references are the same object, which they never are across a round trip.
            .satisfies(a -> assertThat(a.getData()).as("check data").isEqualTo(expected.getData()))
            .satisfies(a -> assertThat(a.getDataContentType()).as("check dataContentType").isEqualTo(expected.getDataContentType()))
            .satisfies(a -> assertThat(a.getPhotoMetadata()).as("check photoMetadata").isEqualTo(expected.getPhotoMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPhotoUpdatableRelationshipsEquals(Photo expected, Photo actual) {
        // empty method
    }
}
