package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlanFeatureAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanFeatureAllPropertiesEquals(PlanFeature expected, PlanFeature actual) {
        assertPlanFeatureAutoGeneratedPropertiesEquals(expected, actual);
        assertPlanFeatureAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanFeatureAllUpdatablePropertiesEquals(PlanFeature expected, PlanFeature actual) {
        assertPlanFeatureUpdatableFieldsEquals(expected, actual);
        assertPlanFeatureUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanFeatureAutoGeneratedPropertiesEquals(PlanFeature expected, PlanFeature actual) {
        assertThat(actual)
            .as("Verify PlanFeature auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanFeatureUpdatableFieldsEquals(PlanFeature expected, PlanFeature actual) {
        assertThat(actual)
            .as("Verify PlanFeature relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlanFeatureUpdatableRelationshipsEquals(PlanFeature expected, PlanFeature actual) {
        assertThat(actual)
            .as("Verify PlanFeature relationships")
            .satisfies(a -> assertThat(a.getPlan()).as("check plan").isEqualTo(expected.getPlan()));
    }
}
