package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PlatformServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformServiceAllPropertiesEquals(PlatformService expected, PlatformService actual) {
        assertPlatformServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertPlatformServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformServiceAllUpdatablePropertiesEquals(PlatformService expected, PlatformService actual) {
        assertPlatformServiceUpdatableFieldsEquals(expected, actual);
        assertPlatformServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformServiceAutoGeneratedPropertiesEquals(PlatformService expected, PlatformService actual) {
        assertThat(actual)
            .as("Verify PlatformService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformServiceUpdatableFieldsEquals(PlatformService expected, PlatformService actual) {
        assertThat(actual)
            .as("Verify PlatformService relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getHost()).as("check host").isEqualTo(expected.getHost()))
            .satisfies(a -> assertThat(a.getPort()).as("check port").isEqualTo(expected.getPort()))
            .satisfies(a -> assertThat(a.getPlane()).as("check plane").isEqualTo(expected.getPlane()))
            .satisfies(a -> assertThat(a.getHealth()).as("check health").isEqualTo(expected.getHealth()))
            .satisfies(a -> assertThat(a.getResponseMs()).as("check responseMs").isEqualTo(expected.getResponseMs()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatformServiceUpdatableRelationshipsEquals(PlatformService expected, PlatformService actual) {
        // empty method
    }
}
