package net.jojoaddison.domain;

import static net.jojoaddison.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PricingPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingPlanAllPropertiesEquals(PricingPlan expected, PricingPlan actual) {
        assertPricingPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertPricingPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingPlanAllUpdatablePropertiesEquals(PricingPlan expected, PricingPlan actual) {
        assertPricingPlanUpdatableFieldsEquals(expected, actual);
        assertPricingPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingPlanAutoGeneratedPropertiesEquals(PricingPlan expected, PricingPlan actual) {
        assertThat(actual)
            .as("Verify PricingPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingPlanUpdatableFieldsEquals(PricingPlan expected, PricingPlan actual) {
        assertThat(actual)
            .as("Verify PricingPlan relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getFeatures()).as("check features").isEqualTo(expected.getFeatures()))
            .satisfies(a -> assertThat(a.getBillingCycle()).as("check billingCycle").isEqualTo(expected.getBillingCycle()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingPlanUpdatableRelationshipsEquals(PricingPlan expected, PricingPlan actual) {
        // empty method
    }
}
