package net.jojoaddison.domain;

import static net.jojoaddison.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProfessionalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAllPropertiesEquals(Professional expected, Professional actual) {
        assertProfessionalAutoGeneratedPropertiesEquals(expected, actual);
        assertProfessionalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAllUpdatablePropertiesEquals(Professional expected, Professional actual) {
        assertProfessionalUpdatableFieldsEquals(expected, actual);
        assertProfessionalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalAutoGeneratedPropertiesEquals(Professional expected, Professional actual) {
        assertThat(actual)
            .as("Verify Professional auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalUpdatableFieldsEquals(Professional expected, Professional actual) {
        assertThat(actual)
            .as("Verify Professional relevant properties")
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getSpeciality()).as("check speciality").isEqualTo(expected.getSpeciality()))
            .satisfies(a -> assertThat(a.getLicenceNumber()).as("check licenceNumber").isEqualTo(expected.getLicenceNumber()))
            .satisfies(a -> assertThat(a.getVerification()).as("check verification").isEqualTo(expected.getVerification()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPatientCount()).as("check patientCount").isEqualTo(expected.getPatientCount()))
            .satisfies(a -> assertThat(a.getCaseCount()).as("check caseCount").isEqualTo(expected.getCaseCount()))
            .satisfies(a -> assertThat(a.getVisitCount()).as("check visitCount").isEqualTo(expected.getVisitCount()))
            .satisfies(a ->
                assertThat(a.getRating()).as("check rating").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRating())
            )
            .satisfies(a -> assertThat(a.getJoinedOn()).as("check joinedOn").isEqualTo(expected.getJoinedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfessionalUpdatableRelationshipsEquals(Professional expected, Professional actual) {
        assertThat(actual)
            .as("Verify Professional relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()))
            .satisfies(a -> assertThat(a.getTeam()).as("check team").isEqualTo(expected.getTeam()))
            .satisfies(a -> assertThat(a.getHub()).as("check hub").isEqualTo(expected.getHub()));
    }
}
