package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RosterWeekAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterWeekAllPropertiesEquals(RosterWeek expected, RosterWeek actual) {
        assertRosterWeekAutoGeneratedPropertiesEquals(expected, actual);
        assertRosterWeekAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterWeekAllUpdatablePropertiesEquals(RosterWeek expected, RosterWeek actual) {
        assertRosterWeekUpdatableFieldsEquals(expected, actual);
        assertRosterWeekUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterWeekAutoGeneratedPropertiesEquals(RosterWeek expected, RosterWeek actual) {
        assertThat(actual)
            .as("Verify RosterWeek auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterWeekUpdatableFieldsEquals(RosterWeek expected, RosterWeek actual) {
        assertThat(actual)
            .as("Verify RosterWeek relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getPublished()).as("check published").isEqualTo(expected.getPublished()))
            .satisfies(a -> assertThat(a.getPublishedAt()).as("check publishedAt").isEqualTo(expected.getPublishedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterWeekUpdatableRelationshipsEquals(RosterWeek expected, RosterWeek actual) {
        // empty method
    }
}
