package net.jojoaddison.domain;

import static net.jojoaddison.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ServicePlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePlanAllPropertiesEquals(ServicePlan expected, ServicePlan actual) {
        assertServicePlanAutoGeneratedPropertiesEquals(expected, actual);
        assertServicePlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePlanAllUpdatablePropertiesEquals(ServicePlan expected, ServicePlan actual) {
        assertServicePlanUpdatableFieldsEquals(expected, actual);
        assertServicePlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePlanAutoGeneratedPropertiesEquals(ServicePlan expected, ServicePlan actual) {
        assertThat(actual)
            .as("Verify ServicePlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePlanUpdatableFieldsEquals(ServicePlan expected, ServicePlan actual) {
        assertThat(actual)
            .as("Verify ServicePlan relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTier()).as("check tier").isEqualTo(expected.getTier()))
            .satisfies(a -> assertThat(a.getTierLabel()).as("check tierLabel").isEqualTo(expected.getTierLabel()))
            .satisfies(a ->
                assertThat(a.getMonthlyPrice())
                    .as("check monthlyPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMonthlyPrice())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getSummary()).as("check summary").isEqualTo(expected.getSummary()))
            .satisfies(a -> assertThat(a.getFeatured()).as("check featured").isEqualTo(expected.getFeatured()))
            .satisfies(a -> assertThat(a.getSubscriberCount()).as("check subscriberCount").isEqualTo(expected.getSubscriberCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicePlanUpdatableRelationshipsEquals(ServicePlan expected, ServicePlan actual) {
        // empty method
    }
}
