package net.jojoaddison.domain;

import static net.jojoaddison.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ServiceActivityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceActivityAllPropertiesEquals(ServiceActivity expected, ServiceActivity actual) {
        assertServiceActivityAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceActivityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceActivityAllUpdatablePropertiesEquals(ServiceActivity expected, ServiceActivity actual) {
        assertServiceActivityUpdatableFieldsEquals(expected, actual);
        assertServiceActivityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceActivityAutoGeneratedPropertiesEquals(ServiceActivity expected, ServiceActivity actual) {
        assertThat(actual)
            .as("Verify ServiceActivity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceActivityUpdatableFieldsEquals(ServiceActivity expected, ServiceActivity actual) {
        assertThat(actual)
            .as("Verify ServiceActivity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a -> assertThat(a.getDuration()).as("check duration").isEqualTo(expected.getDuration()))
            .satisfies(a -> assertThat(a.getPublished()).as("check published").isEqualTo(expected.getPublished()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceActivityUpdatableRelationshipsEquals(ServiceActivity expected, ServiceActivity actual) {
        assertThat(actual)
            .as("Verify ServiceActivity relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
