package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShiftAssignmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAssignmentAllPropertiesEquals(ShiftAssignment expected, ShiftAssignment actual) {
        assertShiftAssignmentAutoGeneratedPropertiesEquals(expected, actual);
        assertShiftAssignmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAssignmentAllUpdatablePropertiesEquals(ShiftAssignment expected, ShiftAssignment actual) {
        assertShiftAssignmentUpdatableFieldsEquals(expected, actual);
        assertShiftAssignmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAssignmentAutoGeneratedPropertiesEquals(ShiftAssignment expected, ShiftAssignment actual) {
        assertThat(actual)
            .as("Verify ShiftAssignment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAssignmentUpdatableFieldsEquals(ShiftAssignment expected, ShiftAssignment actual) {
        assertThat(actual)
            .as("Verify ShiftAssignment relevant properties")
            .satisfies(a -> assertThat(a.getDayIndex()).as("check dayIndex").isEqualTo(expected.getDayIndex()))
            .satisfies(a -> assertThat(a.getShiftDate()).as("check shiftDate").isEqualTo(expected.getShiftDate()))
            .satisfies(a -> assertThat(a.getShift()).as("check shift").isEqualTo(expected.getShift()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShiftAssignmentUpdatableRelationshipsEquals(ShiftAssignment expected, ShiftAssignment actual) {
        assertThat(actual)
            .as("Verify ShiftAssignment relationships")
            .satisfies(a -> assertThat(a.getWeek()).as("check week").isEqualTo(expected.getWeek()))
            .satisfies(a -> assertThat(a.getProfessional()).as("check professional").isEqualTo(expected.getProfessional()));
    }
}
