package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemCatalogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */

    /*
     * createdBy / createdDate / modifiedBy / modifiedDate are deliberately NOT compared here.
     *
     * They are stamped server-side by AuditingEntityCallback and are no longer part of the contract
     * a client controls, so asserting that a value sent in a request comes back unchanged would be
     * asserting the vulnerability this replaced — any caller could PUT "modifiedBy":"somebody-else"
     * and have it stored as authoritative. The stamping behaviour itself is covered by AuditingIT.
     */
    public static void assertSystemCatalogAllPropertiesEquals(SystemCatalog expected, SystemCatalog actual) {
        assertSystemCatalogAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemCatalogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemCatalogAllUpdatablePropertiesEquals(SystemCatalog expected, SystemCatalog actual) {
        assertSystemCatalogUpdatableFieldsEquals(expected, actual);
        assertSystemCatalogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemCatalogAutoGeneratedPropertiesEquals(SystemCatalog expected, SystemCatalog actual) {
        assertThat(actual)
            .as("Verify SystemCatalog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemCatalogUpdatableFieldsEquals(SystemCatalog expected, SystemCatalog actual) {
        assertThat(actual)
            .as("Verify SystemCatalog relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemCatalogUpdatableRelationshipsEquals(SystemCatalog expected, SystemCatalog actual) {
        // empty method
    }
}
