package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemCatalogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemCatalogAllPropertiesEquals(SystemCatalog expected, SystemCatalog actual) {
        assertSystemCatalogAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemCatalogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemCatalogAllUpdatablePropertiesEquals(SystemCatalog expected, SystemCatalog actual) {
        assertSystemCatalogUpdatableFieldsEquals(expected, actual);
        assertSystemCatalogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemCatalogAutoGeneratedPropertiesEquals(SystemCatalog expected, SystemCatalog actual) {
        assertThat(actual)
            .as("Verify SystemCatalog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemCatalogUpdatableFieldsEquals(SystemCatalog expected, SystemCatalog actual) {
        assertThat(actual)
            .as("Verify SystemCatalog relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getModifiedDate()).as("check modifiedDate").isEqualTo(expected.getModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getModifiedBy()).as("check modifiedBy").isEqualTo(expected.getModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemCatalogUpdatableRelationshipsEquals(SystemCatalog expected, SystemCatalog actual) {
        // empty method
    }
}
