package net.jojoaddison.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserOptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserOptionAllPropertiesEquals(UserOption expected, UserOption actual) {
        assertUserOptionAutoGeneratedPropertiesEquals(expected, actual);
        assertUserOptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserOptionAllUpdatablePropertiesEquals(UserOption expected, UserOption actual) {
        assertUserOptionUpdatableFieldsEquals(expected, actual);
        assertUserOptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserOptionAutoGeneratedPropertiesEquals(UserOption expected, UserOption actual) {
        assertThat(actual)
            .as("Verify UserOption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserOptionUpdatableFieldsEquals(UserOption expected, UserOption actual) {
        assertThat(actual)
            .as("Verify UserOption relevant properties")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getUserRef()).as("check userRef").isEqualTo(expected.getUserRef()))
            .satisfies(a -> assertThat(a.getMetadata()).as("check metadata").isEqualTo(expected.getMetadata()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserOptionUpdatableRelationshipsEquals(UserOption expected, UserOption actual) {
        // empty method
    }
}
