package net.jojoaddison.domain;

import static net.jojoaddison.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VendorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorAllPropertiesEquals(Vendor expected, Vendor actual) {
        assertVendorAutoGeneratedPropertiesEquals(expected, actual);
        assertVendorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorAllUpdatablePropertiesEquals(Vendor expected, Vendor actual) {
        assertVendorUpdatableFieldsEquals(expected, actual);
        assertVendorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorAutoGeneratedPropertiesEquals(Vendor expected, Vendor actual) {
        assertThat(actual)
            .as("Verify Vendor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorUpdatableFieldsEquals(Vendor expected, Vendor actual) {
        assertThat(actual)
            .as("Verify Vendor relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getServiceSummary()).as("check serviceSummary").isEqualTo(expected.getServiceSummary()))
            .satisfies(a -> assertThat(a.getContactName()).as("check contactName").isEqualTo(expected.getContactName()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getContractNote()).as("check contractNote").isEqualTo(expected.getContractNote()))
            .satisfies(a -> assertThat(a.getContractRenewsOn()).as("check contractRenewsOn").isEqualTo(expected.getContractRenewsOn()))
            .satisfies(a -> assertThat(a.getOrderCount()).as("check orderCount").isEqualTo(expected.getOrderCount()))
            .satisfies(a ->
                assertThat(a.getSpendToDate())
                    .as("check spendToDate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSpendToDate())
            )
            .satisfies(a ->
                assertThat(a.getRating()).as("check rating").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRating())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVendorUpdatableRelationshipsEquals(Vendor expected, Vendor actual) {
        // empty method
    }
}
